name: Build and Deploy
on:
  push:
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install
        run: yarn install

      - name: build npm package
        run: yarn build

      - name: publish npm package
        if: contains(github.ref, 'main')
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_KEY }}
